image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - |
      {
        npm ci &&
        npm run build &&
        mv ./docs/.vuepress/dist ./dist
      }
  artifacts:
    paths:
      - dist
    expire_in: 1 week

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build
  script:
    - mv dist public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master # this job will affect only the 'master' branch
